import { action as mobxAction } from 'mobx';

export {
  Reaction,
  isBoxedObservable,
  isObservableArray,
  isObservableMap,
  isObservableSet,
  isObservableObject,
  observable,
  computed,
  isObservable,
  isObservableProp,
  isComputed,
  isComputedProp,
  observe,
  intercept,
  autorun,
  reaction,
  when,
  isAction,
  runInAction,
  keys,
  values,
  entries,
  set,
  remove,
  has,
  get,
  onBecomeObserved,
  onBecomeUnobserved,
  toJS,
  trace,
  isArrayLike,
} from "mobx";

export const action = mobxAction.bound;